runtime: nodejs12
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'
  API_URL: 'https://classical-for-everyone.ue.r.appspot.com'